# Generated by Django 3.0.2 on 2020-01-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_zip_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.IntegerField()),
                ('r_id', models.IntegerField()),
                ('sender_name', models.CharField(max_length=1000)),
                ('desc', models.CharField(max_length=1000)),
                ('txn_amt', models.CharField(max_length=100)),
                ('txn_id', models.CharField(max_length=50)),
                ('txn_date', models.CharField(max_length=100)),
            ],
        ),
    ]
