# Generated by Django 3.0.2 on 2020-01-19 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_transactions'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='transactions',
            table='transactions',
        ),
    ]
