# Generated by Django 3.0.2 on 2020-01-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200119_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='currency',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
