# Generated by Django 3.0.2 on 2020-01-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_transactions_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestMoney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.IntegerField()),
                ('r_id', models.IntegerField()),
                ('r_name', models.CharField(max_length=1000)),
                ('r_email', models.EmailField(max_length=254)),
                ('r_amount', models.FloatField()),
                ('currency', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=1000)),
                ('due_date', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'request_money',
            },
        ),
    ]
