# Generated by Django 3.0.2 on 2020-01-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_requestmoney'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmoney',
            name='status',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
