# Generated by Django 3.0.2 on 2020-01-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_requestmoney_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='receiver_name',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
