# Generated by Django 3.0.2 on 2020-01-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_transactions_receiver_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmoney',
            name='r_date',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestmoney',
            name='sender',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
