# Generated by Django 3.0.2 on 2020-01-30 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20200130_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.IntegerField()),
                ('card_issuer', models.CharField(max_length=100)),
                ('card_num', models.CharField(max_length=100)),
                ('exp_date', models.CharField(max_length=10)),
                ('cvv_no', models.CharField(max_length=10)),
                ('card_name', models.CharField(max_length=1000)),
            ],
        ),
    ]
