# Generated by Django 3.0.2 on 2020-01-30 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_card'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='card',
            table='card',
        ),
    ]
