# Generated by Django 3.0.2 on 2020-01-30 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20200130_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
