# Generated by Django 3.0.2 on 2020-02-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_banks'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('acct_type', models.CharField(max_length=100)),
                ('bank_country', models.CharField(max_length=100)),
                ('bank_name', models.CharField(max_length=100)),
                ('acct_name', models.CharField(max_length=1000)),
                ('acct_no', models.CharField(max_length=100)),
                ('swift_code', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'bank_account',
            },
        ),
    ]
